apiVersion: v1
kind: ConfigMap
metadata:
  name: data-controller-configmap
  namespace: arc-data-services-installer
data:
  control.json: |
    {
        "apiVersion": "arcdata.microsoft.com/v5",
        "kind": "DataController",
        "metadata": {
            "name": "datacontroller"
        },
        "spec": {
            "infrastructure": "azure",
            "credentials": {
                "serviceAccount": "sa-arc-controller",
                "dockerRegistry": "arc-private-registry",
                "domainServiceAccount": "domain-service-account-secret"
            },
            "docker": {
                "registry": "mcr.microsoft.com",
                "repository": "arcdata",
                "imageTag": "v1.7.0_2022-05-24",
                "imagePullPolicy": "Always"
            },
            "storage": {
                "data": {
                    "className": "managed-csi",
                    "accessMode": "ReadWriteOnce",
                    "size": "15Gi"
                },
                "logs": {
                    "className": "managed-csi",
                    "accessMode": "ReadWriteOnce",
                    "size": "10Gi"
                }
            },
            "security": {
                "allowDumps": true,
                "allowNodeMetricsCollection": true,
                "allowPodMetricsCollection": true
            },
            "services": [
                {
                    "name": "controller",
                    "serviceType": "LoadBalancer",
                    "port": 30080
                }
            ],
            "settings": {
                "azure": {
                    "autoUploadMetrics": "true",
                    "autoUploadLogs": "false"
                },
                "controller": {
                    "logs.rotation.size": "5000",
                    "logs.rotation.days": "7"
                },
                "ElasticSearch": {
                    "vm.max_map_count": "-1"
                }
            }
        }
    }
