apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-arc-data-services-installer-job
  namespace: arc-data-services-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-arc-data-services-installer-job
subjects:
  - kind: ServiceAccount
    namespace: arc-data-services-installer
    name: kube-arc-data-services-installer-job
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io